"""
Main Python file from which the Flask app is to be run. The app is hosted on localhost, port 3000.
"""
from datetime import timedelta

from flask import Flask, redirect, url_for, render_template

from health_warehouse.blueprints.account import account

try:
    # Windows implementation to open the HTML documentation file in the browser.
    from os import startfile

    os_ = 'windows'

except ImportError:
    # MacOS or Linux implementation to open the HTML documentation file in the browser.
    from subprocess import call

    os_ = 'unix'

app = Flask(__name__, static_folder='static', template_folder='templates')
app.secret_key = '238746bq2837o64478e6o'
app.permanent_session_lifetime = timedelta(minutes=10)

app.register_blueprint(account, url_prefix='/account')


@app.route('/')
def homepage():
    """
    Main homepage for the project containing an overview of the project.

    :return: Rendering of the template for 'homepage.html'.
    :rtype: str
    """
    return render_template('homepage/homepage.html')


@app.route('/project')
def project_redirect():
    """
    Redirect to the main project login page from the homepage.

    :return: Redirect to the login page.
    :rtype: Response
    """
    return redirect(url_for('account.login'))


@app.route('/details')
def details():
    """
    Main project details page containing detailed information docs the project.

    :return: Rendering of the template for 'homepage-project-details.html'.
    :rtype: str
    """
    return render_template('homepage/details.html')


@app.route('/docs')
def docs():
    """
    Main project documentation page generated by Sphinx. Since the documentation HTML file is not in the "templates"
    folder, it is rendered externally using either "os.startfile()" on Windows or subprocess.call() on macOS or Linux.
    This opens the documentation in a new tab and the original tab is redirected back to the homepage of the project.

    :return: Redirect to the homepage.
    :rtype: Response
    """
    doc_path = ''

    if os_ == 'windows':
        return 'Windows docs!'
    else:
        return 'Unix docs!'


@app.route('/acknowledgements')
def acknowledgement():
    """
    Project acknowledgements page.

    :return: Rendering of the template for 'homepage-acknowledgements.html'.
    :rtype: str
    """
    return render_template('homepage/acknowledgements.html')


if __name__ == '__main__':
    app.run()
